### ISSUE TITLE
save image default as .png

### ISSUE THREAD

**Issue by rverbrugghe** [thocoo/gamma-desk#5]
When saving an image it will use .bmp as default. However this will also convert the image from 16b to 8b.
If saved as .png it will keep the image in 16b

**Comment by thocoo** [comment]
Can you check if bmp is the default because it is the first in alphabetic order?

**Comment by thocoo** [comment]
Note that the automatic conversion from 16b to 8b for the BMP is done automatic by the imageio package.
So I can not fixed that this automatic happens. But I fixed the default to by TIFF.
Because it can handle more array types then BMP or PNG.
Some advise: Always use a good suffix when you save a file. Don't count on the gui of adding a suffix for you.
